version: 2

build:
   image: latest

sphinx:
  configuration: docs/conf.py

python:
   version: 3.7
   install:
      - method: pip
        path: .

conda:
   environment: conda/environments/builddocs_py37.yml
