# Copyright (c) 2019-2023, NVIDIA CORPORATION.

# Usage:
#   conda build -c conda-forge .
{% set data = load_file_data("pyproject.toml") %}

{% set version = environ['RAPIDS_PACKAGE_VERSION'].strip('""').lstrip('v') %}
{% set py_version = environ['CONDA_PY'] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: dask-cuda
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script:
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    {% for e in data.get("project", {}).get("scripts", {}).items() %}
    - {{ e|join(" = ") }}
    {% endfor %}

requirements:
  host:
    - python
    - pip
    - tomli
  run:
    - python
    {% for r in data.get("project", {}).get("dependencies", []) %}
    - {{ r }}
    {% endfor %}

test:
  imports:
    - dask_cuda
  commands:
    - dask cuda --help
    {% for e in data.get("project", {}).get("scripts", {}).keys() %}
    - {{ e }} --help
    - {{ e|replace("-", " ") }} --help
    {% endfor %}

about:
  home: {{ data.get("project", {}).get("urls", {}).get("Homepage", "") }}
  license: {{ data.get("project", {}).get("license", {}).get("text", "") }}
  license_file:
    {% for e in data.get("tool", {}).get("setuptools", {}).get("license-files", []) %}
    - ../../../{{ e }}
    {% endfor %}
  summary: {{ data.get("project", {}).get("description", "") }}
  dev_url: {{ data.get("project", {}).get("urls", {}).get("Source", "") }}
  doc_url: {{ data.get("project", {}).get("urls", {}).get("Documentation", "") }}
