# Copyright (c) 2019, NVIDIA CORPORATION.

# Usage:
#   conda build -c conda-forge -c defaults .
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set py_version=environ.get('CONDA_PY', 36) %}
package:
  name: dask-cuda
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ git_revision_count }}
  string: py{{ py_version }}_{{ git_revision_count }}
  script_env:
    - VERSION_SUFFIX

requirements:
  build:
    - python x.x
    - setuptools
  run:
    - python x.x
    - dask-core >=2.4.0
    - distributed >=2.7.0
    - pynvml >=8.0.3
    - numpy >=1.16.0
    - numba >=0.40.1

test:
  imports:
    - dask_cuda


about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_file: ../../../LICENSE
  summary: dask-cuda library
