# Copyright (c) 2019-2023, NVIDIA CORPORATION.

# Usage:
#   conda build -c conda-forge .
{% set data = load_file_data("pyproject.toml") %}

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set py_version = environ['CONDA_PY'] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: dask-cuda
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script:
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    {% for e in data.get("project", {}).get("scripts", {}).items() %}
    - {{ e|join(" = ") }}
    {% endfor %}

requirements:
  host:
    - python
    - pip
    - tomli
    - versioneer >=0.24
  run:
    - python
    {% for r in data.get("project", {}).get("dependencies", []) %}
    - {{ r }}
    {% endfor %}

test:
  imports:
    - dask_cuda
  commands:
    - dask cuda --help
    {% for e in data.get("project", {}).get("scripts", {}).keys() %}
    - {{ e }} --help
    - {{ e|replace("-", " ") }} --help
    {% endfor %}

about:
  home: https://rapids.ai/
  license: Apache-2.0
  license_file: ../../../LICENSE
  summary: dask-cuda library
