# Copyright (c) 2019-2023, NVIDIA CORPORATION.

# Usage:
#   conda build -c conda-forge .
{% set data = load_file_data("pyproject.toml") %}

{% set version = environ['RAPIDS_PACKAGE_VERSION'].strip('""').lstrip('v') %}
{% set py_version = environ['CONDA_PY'] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: dask-cuda
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script:
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    {% for entrypoint in data["project"]["scripts"] %}
    - {{ entrypoint ~ ' = ' ~ data["project"]["scripts"][entrypoint] }}
    {% endfor %}

requirements:
  host:
    - python
    - pip
    - rapids-build-backend>=0.3.0,<0.4.0.dev0
  run:
    - python
    {% for r in data["project"]["dependencies"] %}
    - {{ r }}
    {% endfor %}

test:
  imports:
    - dask_cuda
  commands:
    - dask cuda --help
    {% for entrypoint in data["project"]["scripts"] %}
    - {{ entrypoint }} --help
    - {{ entrypoint|replace("-", " ") }} --help
    {% endfor %}

about:
  home: {{ data["project"]["urls"]["Homepage"] }}
  license: {{ data["project"]["license"]["text"] }}
  license_file:
    {% for e in data["tool"]["setuptools"]["license-files"] %}
    - ../../../{{ e }}
    {% endfor %}
  summary: {{ data["project"]["description"] }}
  dev_url: {{ data["project"]["urls"]["Source"] }}
  doc_url: {{ data["project"]["urls"]["Documentation"] }}
