# Copyright (c) 2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: dask-cuda
  version: ${{ version }}

source:
  path: ../../..

build:
  noarch: python
  string: py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
  script:
    content: |
      python -m pip install . -vv
  python:
    entry_points:
      - dask-cuda-worker = dask_cuda.cli:worker
      - dask-cuda-config = dask_cuda.cli:config

requirements:
  host:
    - python
    - pip
    - rapids-build-backend >=0.4.0,<0.5.0dev0
    - setuptools >=64.0.0
  run:
    - python
    - click >=8.1
    - numba >=0.60.0,<0.62.0a0
    - numba-cuda >=0.19.1,<0.20.0a0
    - numpy >=1.23,<3.0a0
    # 'nvidia-ml-py' provides the 'pynvml' module, since v12.560.30
    # ref: https://github.com/conda-forge/nvidia-ml-py-feedstock/pull/24
    - nvidia-ml-py>=12.560.30
    - pandas >=1.3
    - rapids-dask-dependency =${{ minor_version }}
    - zict >=2.0.0

tests:
  - python:
      imports:
        - dask_cuda
      pip_check: false
  - script:
      - dask cuda --help
      - dask cuda worker --help
      - dask cuda config --help

about:
  homepage: ${{ load_from_file("pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("pyproject.toml").project.license.text }}
  summary: ${{ load_from_file("pyproject.toml").project.description }}
