name: Trigger Nightly Build and Test Pipelines

on:
  schedule:
    - cron: "0 5 * * *"  # 5am UTC / 1am EST
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
      date:
        required: true
        type: string
      sha:
        required: true
        type: string
      build_type:
        type: string
        default: branch

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      build_type: ${{ inputs.build_type || 'branch' }}
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}

  test:
    needs: build
    uses: ./.github/workflows/test.yaml
    with:
      build_type: ${{ inputs.build_type || 'branch' }}
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
