name: test

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
      date:
        required: true
        type: string
      sha:
        required: true
        type: string

jobs:
  conda-python-tests:
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/conda-python-tests.yaml@branch-23.06
    with:
      # TODO: remove the `matrix_filter` line after `cudf` is publishing `3.9`
      # packages. also remove the line in `pr.yaml`
      matrix_filter: map(select(.PY_VER == "3.10"))
      build_type: nightly
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
