name: Test Dask-CUDA with UCXX

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
      date:
        required: true
        type: string
      sha:
        required: true
        type: string
      build_type:
        type: string
        default: nightly

jobs:
  conda-python-ucxx-tests:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-tests.yaml@branch-25.06
    with:
      build_type: ${{ inputs.build_type }}
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
      gh_token: ${{ github.token }}
      script: ci/test_python_ucxx.sh
